# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel:
    - chef-ws-notify
    - chef-infra-notify
    - inspec-notify

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true

subscriptions:
  - workload: artifact_published:stable:chef-dk:*
    actions:
      - bash:.expeditor/update_version.sh
  - workload: artifact_published:stable:chef:*
    actions:
      - bash:.expeditor/update_version.sh
  - workload: artifact_published:stable:inspec:*
    actions:
      - bash:.expeditor/update_version.sh
  - workload: artifact_published:stable:chef-workstation:*
    actions:
      - bash:.expeditor/update_version.sh

pipelines:
  - verify:
      description: Pull Request validation tests
      public: true
